"""Play the lesson out after the correct move, with coaching on every move.

Why this exists
---------------
A player answered Re4 on the Lucena lesson and the app jumped straight to the
next puzzle. They never saw the pawn promote, so the move they had just been
asked for meant nothing. "It should take me through the complete sequence that
promotes the pawn, so the Re4 idea makes sense."

Nothing in the live path did that. `endgame_theory_service` returns
`"demonstrated": is_last`, which only reports that you reached the final
position -- no continuation is generated or played anywhere.

How the line is produced
------------------------
Generated by Stockfish, never authored. Three attempts at hand-writing the
Lucena bridge were each engine-scored as a DRAW (+0 cp, 96% draw), so the
technique does not get written here by anyone. White plays the engine's best
move. Black plays its best CHECK when one exists and White is still clearly
winning, because the engine's objectively-best defence wanders off and the
taught idea never appears -- the rook left the fourth rank on move two and Re4
looked pointless.

How the coaching is produced
----------------------------
Two sources, in priority order:

1. A BEAT -- a board fact this module detects itself: the rook reaching the
   fourth rank, a check, the checking piece being captured, the promotion, the
   mate. Beats are pure geometry (`gives_check`, `is_capture`,
   `move.promotion`, `is_checkmate`, square ranks). No judgement about whether
   a move is *good* is made here.

2. Otherwise `caption_pipeline.build_move_teaching_decision` -- the one
   coaching path this codebase permits. It captions the connecting moves so
   this scales to every lesson position without anyone authoring 780 lines of
   chess prose.

The split matters: the central pipeline captions competently but has no idea
it is inside a Lucena lesson, so it narrated the promotion-with-mate as
"d8=Q# is the best move in this position". Beats exist to say the thing the
lesson is actually about, and only where a board fact licenses it.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import chess

logger = logging.getLogger(__name__)

SCHEMA_VERSION = "lesson_continuation.v1"

# Depth for both the line and its evaluations. 18 is what the review pipeline
# uses for stored analysis; the lines here are short and forced.
DEFAULT_DEPTH = 18
DEFAULT_MAX_PLIES = 24

# A defender's check is only played while the side being taught is still
# clearly winning. Below this the "natural try" would be a blunder and the
# lesson would teach a line nobody should play.
DEFENDER_CHECK_MIN_CP = 200

_STOCKFISH_CANDIDATES = ("/usr/games/stockfish", "/usr/local/bin/stockfish", "stockfish")


def _stockfish_path() -> Optional[str]:
    explicit = os.environ.get("STOCKFISH_PATH")
    if explicit and os.path.exists(explicit):
        return explicit
    for path in _STOCKFISH_CANDIDATES:
        if os.path.exists(path):
            return path
    return None


@dataclass
class ContinuationMove:
    """One move of the played-out line, with the coaching shown beside it."""

    ply: int
    san: str
    uci: str
    fen_before: str
    fen_after: str
    mover_is_learner: bool
    beat: Optional[str]
    coaching: str

    def public_dict(self) -> Dict[str, Any]:
        return {
            "ply": self.ply,
            "san": self.san,
            "uci": self.uci,
            "fen_before": self.fen_before,
            "fen_after": self.fen_after,
            "mover_is_learner": self.mover_is_learner,
            "beat": self.beat,
            "coaching": self.coaching,
        }


@dataclass
class Continuation:
    schema_version: str
    start_fen: str
    learner_color: str
    moves: List[ContinuationMove] = field(default_factory=list)
    reached_promotion: bool = False
    reached_mate: bool = False
    unavailable_reason: Optional[str] = None

    def public_dict(self) -> Dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "start_fen": self.start_fen,
            "learner_color": self.learner_color,
            "moves": [m.public_dict() for m in self.moves],
            "reached_promotion": self.reached_promotion,
            "reached_mate": self.reached_mate,
            "unavailable_reason": self.unavailable_reason,
        }


# ─── Beats: board facts only ────────────────────────────────────────────

BEAT_ROOK_TO_SHIELD_RANK = "rook_to_shield_rank"
BEAT_CHECK = "check"
BEAT_CAPTURED_CHECKER = "captured_checker"
BEAT_PROMOTION = "promotion"
BEAT_PROMOTION_MATE = "promotion_mate"
BEAT_MATE = "mate"


def shield_rank_for(board: chess.Board, colour: bool) -> Optional[int]:
    """The rank a rook is sent to so it can block a check later -- or None.

    NOT a constant. "Put your rook on the fourth rank" is Lucena's rule, and it
    only holds because Lucena has a pawn one square from promoting: the king
    walks down to the fifth and the rook interposes one rank below it. Take the
    pawn away and the number means nothing.

    Hardcoding rank 4 made this fire on Philidor, which has no advanced pawn at
    all and sends its rook elsewhere for an entirely different reason -- and the
    lesson then told the player that their CHECKING move "is not attacking
    anything yet".

    So the rank is derived from the pawn, and this returns None unless the
    position actually has the shape the rule describes.
    """
    pawns = [
        sq for sq in board.pieces(chess.PAWN, colour)
        if chess.square_rank(sq) == (6 if colour == chess.WHITE else 1)
    ]
    king = board.king(colour)
    if not pawns or king is None:
        return None
    for pawn in pawns:
        in_front = (
            chess.square_file(king) == chess.square_file(pawn)
            and chess.square_rank(king)
            == chess.square_rank(pawn) + (1 if colour == chess.WHITE else -1)
        )
        if in_front:
            return (
                chess.square_rank(pawn) - 3 if colour == chess.WHITE
                else chess.square_rank(pawn) + 3
            )
    return None


def detect_beat(
    board_before: chess.Board,
    move: chess.Move,
    board_after: chess.Board,
    learner_colour: bool,
) -> Optional[str]:
    """Name what just happened on the board, or None.

    Every branch is a geometric fact. Nothing here decides whether a move was
    good -- that stays with the engine and the caption pipeline.
    """
    mover = board_before.turn
    piece = board_before.piece_at(move.from_square)

    if move.promotion is not None:
        return BEAT_PROMOTION_MATE if board_after.is_checkmate() else BEAT_PROMOTION
    if board_after.is_checkmate():
        return BEAT_MATE

    # The learner's king takes the piece that had been checking it: the checks
    # have run out. Only claimed when the learner was actually in check.
    if (
        mover == learner_colour
        and board_before.is_check()
        and board_before.is_capture(move)
        and piece is not None
        and piece.piece_type == chess.KING
    ):
        return BEAT_CAPTURED_CHECKER

    shield = shield_rank_for(board_before, learner_colour)
    if (
        shield is not None
        and mover == learner_colour
        and piece is not None
        and piece.piece_type == chess.ROOK
        and chess.square_rank(move.to_square) == shield
        and chess.square_rank(move.from_square) != shield
        # A move that gives check is doing something now, not preparing. The
        # line "it is not attacking anything yet" was printed on Ra5+.
        and not board_after.is_check()
    ):
        return BEAT_ROOK_TO_SHIELD_RANK

    if board_after.is_check() and mover != learner_colour:
        return BEAT_CHECK

    return None


def _beat_coaching(
    beat: str,
    board_before: chess.Board,
    move: chess.Move,
    board_after: chess.Board,
    check_index: int = 0,
    is_last_check: bool = False,
) -> str:
    """Plain-English line for a beat. Only states what the beat established."""
    to_sq = chess.square_name(move.to_square)

    if beat == BEAT_ROOK_TO_SHIELD_RANK:
        return (
            f"The rook goes to {to_sq}. It is not attacking anything yet. It is "
            f"getting into position to step in front of a check later."
        )
    if beat == BEAT_CHECK:
        # Said once in full. A defender checks five or six times in these
        # endings and repeating one sentence reads as a broken record. The
        # later lines report progress, and the last one points at the
        # resolution -- which is licensed because the whole continuation was
        # generated and verified to end in promotion before any of this is
        # written.
        if check_index == 0:
            return (
                "And there is the check. This is the problem the plan has to "
                "solve: your king has to answer it before anything else."
            )
        if is_last_check:
            return (
                "The last check. Your king has walked close enough to deal "
                "with the rook for good."
            )
        return "Still checking. Each time, your king walks a little closer."

    if beat == BEAT_CAPTURED_CHECKER:
        captured = board_before.piece_at(move.to_square)
        name = chess.piece_name(captured.piece_type) if captured else "piece"
        # Only claim the pawn is free if the learner still HAS one near
        # promotion. On lucena[2] the defender's check was Rxf7+, taking the
        # pawn, and this still said "nothing is stopping the pawn".
        mover = board_before.turn
        still_advanced = any(
            chess.square_rank(sq) == (6 if mover == chess.WHITE else 1)
            for sq in board_after.pieces(chess.PAWN, mover)
        )
        if still_advanced:
            return (
                f"Your king takes the {name} on {to_sq}. The checks have run "
                f"out, and now nothing is stopping the pawn."
            )
        return f"Your king takes the {name} on {to_sq}. The checks have run out."
    if beat == BEAT_PROMOTION_MATE:
        return (
            f"The pawn reaches {to_sq} and becomes a queen — and that is "
            f"checkmate. This is what the whole plan was for."
        )
    if beat == BEAT_PROMOTION:
        return (
            f"The pawn reaches {to_sq} and becomes a queen. This is what the "
            f"whole plan was for."
        )
    if beat == BEAT_MATE:
        return "That is checkmate."
    return ""


# ─── Line generation ────────────────────────────────────────────────────

def _choose_defender_move(engine, board: chess.Board, learner: bool, depth: int):
    """The defender's most natural try: the check that resists longest.

    Picking any check makes the defender hang pieces; picking the engine's
    best move makes it wander and the lesson's idea never appears. This picks
    the check that leaves the learner with the SMALLEST advantage, and only
    while that advantage is still decisive.
    """
    import chess.engine

    # A check that captures the pawn we are trying to promote ends the
    # demonstration without refuting anything. On lucena[2] the defender
    # played Rxf7+, giving up the rook for the pawn: still winning for the
    # learner, but the line then proves nothing about promoting. Stockfish's
    # own continuation does not play it either.
    advanced = {
        sq for sq in board.pieces(chess.PAWN, learner)
        if chess.square_rank(sq) == (6 if learner == chess.WHITE else 1)
    }
    checks = [
        m for m in board.legal_moves
        if board.gives_check(m) and m.to_square not in advanced
    ]
    best_move = None
    best_cp = None
    for candidate in checks:
        board.push(candidate)
        try:
            info = engine.analyse(board, chess.engine.Limit(depth=depth))
            cp = info["score"].pov(learner).score(mate_score=100000)
        except Exception:
            cp = None
        finally:
            board.pop()
        if cp is None:
            continue
        if best_cp is None or cp < best_cp:
            best_cp, best_move = cp, candidate

    if best_move is not None and best_cp is not None and best_cp >= DEFENDER_CHECK_MIN_CP:
        return best_move

    info = engine.analyse(board, chess.engine.Limit(depth=depth))
    pv = info.get("pv") or []
    return pv[0] if pv else None


def build_continuation(
    fen: str,
    first_move_san: str,
    *,
    depth: int = DEFAULT_DEPTH,
    max_plies: int = DEFAULT_MAX_PLIES,
) -> Continuation:
    """Play the position out from `first_move_san` and caption every move.

    Returns a Continuation whose `unavailable_reason` is set rather than
    raising, so a lesson with no engine available simply behaves as it does
    today instead of failing.
    """
    import chess.engine

    board = chess.Board(fen)
    learner = board.turn
    result = Continuation(
        schema_version=SCHEMA_VERSION,
        start_fen=fen,
        learner_color="white" if learner == chess.WHITE else "black",
    )

    try:
        first = board.parse_san(first_move_san)
    except ValueError:
        result.unavailable_reason = "first move is not legal in this position"
        return result

    path = _stockfish_path()
    if not path:
        result.unavailable_reason = "no engine available"
        return result

    history: List[str] = []
    raw: List[Dict[str, Any]] = []
    try:
        with chess.engine.SimpleEngine.popen_uci(path) as engine:
            move = first
            for ply in range(max_plies):
                fen_before = board.fen()
                san = board.san(move)
                mover_is_learner = board.turn == learner
                before_snapshot = board.copy(stack=False)
                board.push(move)

                beat = detect_beat(before_snapshot, move, board, learner)
                raw.append({
                    "ply": ply, "san": san, "uci": move.uci(),
                    "fen_before": fen_before, "fen_after": board.fen(),
                    "mover_is_learner": mover_is_learner, "beat": beat,
                    "snapshot": before_snapshot, "move": move,
                    "board_after": board.copy(stack=False),
                    "history": list(history),
                })
                history.append(san)

                if move.promotion is not None:
                    result.reached_promotion = True
                if board.is_checkmate():
                    result.reached_mate = True
                if result.reached_promotion or board.is_game_over():
                    break

                if board.turn == learner:
                    info = engine.analyse(board, chess.engine.Limit(depth=depth))
                    pv = info.get("pv") or []
                    move = pv[0] if pv else None
                else:
                    move = _choose_defender_move(engine, board, learner, depth)
                if move is None:
                    break
            # Second pass. Captioning only after the whole line exists is what
            # lets a beat say "the last check" -- during generation there is no
            # way to know which check is the last one.
            beat_plies = [r["ply"] for r in raw if r["beat"]]
            # The last beat before the finish. Moves after it are connective
            # tissue; the finish itself is a beat and still speaks.
            decisive = [p for p in beat_plies if p < (beat_plies[-1] if beat_plies else 0)]
            last_beat_ply = decisive[-1] if decisive else -1
            check_plies = [r["ply"] for r in raw if r["beat"] == BEAT_CHECK]
            last_check_ply = check_plies[-1] if check_plies else None
            check_index = 0
            for r in raw:
                if r["beat"]:
                    coaching = _beat_coaching(
                        r["beat"], r["snapshot"], r["move"], r["board_after"],
                        check_index, r["ply"] == last_check_ply,
                    )
                    if r["beat"] == BEAT_CHECK:
                        check_index += 1
                elif r["ply"] == 0:
                    # The first move IS the lesson's answer. Running it through
                    # a game-review captioner produced "Ke7 is playable. Kg8 was
                    # better." -- naming the WRONG move as better than the one
                    # the lesson teaches -- and "The curriculum starts with d4"
                    # in a rook endgame. The surrounding UI already names this
                    # move; it does not need a verdict on it.
                    coaching = ""
                elif r["ply"] > last_beat_ply:
                    # Past the last thing worth naming. The central pipeline
                    # is a game-review captioner and does not know it is in a
                    # lesson, so on the shuffling moves between the decisive
                    # capture and the promotion it produced filler -- "Look at
                    # what it attacks now" three times in a row. Silence reads
                    # better than filler, and the board still moves.
                    coaching = ""
                else:
                    coaching = _central_caption(
                        engine, r["snapshot"], r["move"], r["san"],
                        r["history"], learner, depth,
                    )
                result.moves.append(ContinuationMove(
                    ply=r["ply"], san=r["san"], uci=r["uci"],
                    fen_before=r["fen_before"], fen_after=r["fen_after"],
                    mover_is_learner=r["mover_is_learner"],
                    beat=r["beat"], coaching=coaching,
                ))
    except Exception as exc:  # engine crash, timeout, bad binary
        logger.warning("lesson continuation failed for %s: %s", fen, exc)
        if not result.moves:
            result.unavailable_reason = "engine error"
    return result


def _central_caption(engine, board_before, move, san, history, learner, depth) -> str:
    """Caption a connecting move through the one permitted coaching path."""
    import chess.engine

    try:
        from services.caption_pipeline import (
            CrossMoveState,
            MoveInputs,
            build_move_teaching_decision,
        )

        info_before = engine.analyse(board_before, chess.engine.Limit(depth=depth))
        best_pv = info_before.get("pv") or []
        best_san = board_before.san(best_pv[0]) if best_pv else None
        eval_before = info_before["score"].white().score(mate_score=10000)

        after = board_before.copy(stack=False)
        after.push(move)
        info_after = engine.analyse(after, chess.engine.Limit(depth=depth))
        eval_after = info_after["score"].white().score(mate_score=10000)

        mover_is_white = board_before.turn == chess.WHITE
        sign = 1 if mover_is_white else -1
        cp_loss = max(0, int((eval_before - eval_after) * sign))

        decision = build_move_teaching_decision(
            MoveInputs(
                fen_before=board_before.fen(),
                played_san=san,
                mover_is_user=(board_before.turn == learner),
                mover_is_white=mover_is_white,
                user_color="white" if learner == chess.WHITE else "black",
                full_move_number=board_before.fullmove_number,
                move_history_san=list(history),
                best_move_san=best_san,
                eval_before_cp=eval_before,
                eval_after_cp=eval_after,
                cp_loss=cp_loss,
            ),
            CrossMoveState(),
        )
        # decision.caption is a TextSurface(caption=..., rule_name=...), not a
        # string. Taking str() of it renders the dataclass repr, which shipped
        # "TextSurface(caption='...', rule_name='...')" straight into the
        # lesson on the first run.
        # The TextSurface lives on decision.text, not decision.caption, and
        # TextSurface itself has the string under .caption. Reading the wrong
        # one first rendered the dataclass repr into the lesson
        # ("TextSurface(caption='...', rule_name='...')"); reading the other
        # wrong one returned empty. Both shipped in one sitting.
        surface = getattr(decision, "text", None)
        text = getattr(surface, "caption", None)
        if text is None:
            text = surface if isinstance(surface, str) else ""
        return str(text or "").strip()
    except Exception as exc:
        logger.warning("central caption failed for %s: %s", san, exc)
        return ""
