"""
Threat verifier — Category 4 of the Parth-bug taxonomy.

Many "your X on Y can be taken for free" claims in coaching text are
generated by 1-ply static checks (is the square defended right now?).
They miss tactical refutations that recover material in 2-4 plies.

Example: fb_159fc121ec61. Black knight on e4 looks "free" (white bishop
on d3 attacks it, no defender). Coach says "your knight on e4 can be
taken for free." But after Bxe4, black plays d5 attacking the bishop;
bishop's only retreat is d3; black plays e4 forking knight and bishop.
Material is recovered. The "free" claim is wrong over 4 plies.

This module runs Stockfish on the post-capture position. If the
engine's eval (from the user's perspective) shows the user has lost
significantly less than the captured piece's value, there's
compensation — don't say "free."

Defensive: if engine isn't available, returns True (claim allowed).
The audit-time verifier (content_correctness_audit Phase 2) catches
these post-hoc; this module catches them at emit-time.
"""
from __future__ import annotations

import atexit
import logging
import threading
from typing import Optional

import chess
import chess.engine

logger = logging.getLogger(__name__)

# Process-local Stockfish singleton — verification calls reuse one warm
# engine instead of spawning Stockfish per call. Lazy-init on first use,
# cleanup at process exit. Wrapped in a lock so concurrent coaching
# requests don't trample each other.
_engine_lock = threading.Lock()
_engine_singleton: Optional[chess.engine.SimpleEngine] = None
_engine_init_failed = False


def _get_singleton_engine() -> Optional[chess.engine.SimpleEngine]:
    """Return the process-local Stockfish handle, or None if the binary
    isn't available (e.g. running outside the production container).
    Failure is sticky: if init fails once, subsequent calls return None
    immediately rather than retrying repeatedly."""
    global _engine_singleton, _engine_init_failed
    if _engine_singleton is not None:
        return _engine_singleton
    if _engine_init_failed:
        return None
    with _engine_lock:
        if _engine_singleton is not None:
            return _engine_singleton
        if _engine_init_failed:
            return None
        try:
            from config import STOCKFISH_PATH
            _engine_singleton = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)
            atexit.register(_quit_engine)
        except Exception as exc:
            logger.warning(
                f"[threat_verifier] Stockfish singleton init failed "
                f"({exc}); verification disabled this process."
            )
            _engine_init_failed = True
            _engine_singleton = None
    return _engine_singleton


def _quit_engine() -> None:
    global _engine_singleton
    if _engine_singleton is not None:
        try:
            _engine_singleton.quit()
        except Exception:
            pass
        _engine_singleton = None

# Material values in centipawns — match move_comparison.PIECE_VALUES * 100
_PIECE_VAL_CP = {
    chess.PAWN: 100,
    chess.KNIGHT: 300,
    chess.BISHOP: 300,
    chess.ROOK: 500,
    chess.QUEEN: 900,
    chess.KING: 0,
}

# A "free" claim is wrong if the user recovers more than this fraction
# of the captured piece's value within the engine's analysis window.
_RECOVERY_THRESHOLD = 0.5

# Engine depth for verification. Higher = more accurate but slower.
# 10 plies catches the typical 2-3 ply tactical recoveries Parth flagged
# without making each verification take seconds.
_VERIFY_DEPTH = 10


def free_capture_claim_is_credible(
    fen_before_opp_move: str,
    opp_capture_move_uci: str,
    user_color: chess.Color,
    engine: Optional[chess.engine.SimpleEngine] = None,
) -> bool:
    """Returns True if the 'piece can be taken for free' claim is
    actually true at engine depth — i.e., the user really does lose
    that material with no compensation.

    Returns True if engine is None (cannot verify -> trust the caller's
    static check; matches existing behavior).

    Returns False if the engine sees the user recovering significant
    material in subsequent moves -> claim should be suppressed.
    """
    if engine is None:
        return True

    try:
        board = chess.Board(fen_before_opp_move)
    except ValueError:
        return True

    try:
        capture_move = chess.Move.from_uci(opp_capture_move_uci)
    except Exception:
        return True

    if capture_move not in board.legal_moves:
        return True

    captured_piece = board.piece_at(capture_move.to_square)
    if not captured_piece or captured_piece.color != user_color:
        return True
    captured_value = _PIECE_VAL_CP.get(captured_piece.piece_type, 0)
    if captured_value == 0:
        return True  # don't bother for pawns

    try:
        # Eval before the capture (user's perspective).
        info_pre = engine.analyse(board, chess.engine.Limit(depth=_VERIFY_DEPTH))
        eval_pre = info_pre.get("score")
        if eval_pre is None:
            return True
        eval_pre_cp = eval_pre.pov(user_color).score(mate_score=10000)
        if eval_pre_cp is None:
            return True

        # Apply the capture and search again.
        board.push(capture_move)
        info_post = engine.analyse(board, chess.engine.Limit(depth=_VERIFY_DEPTH))
        eval_post = info_post.get("score")
        if eval_post is None:
            return True
        eval_post_cp = eval_post.pov(user_color).score(mate_score=10000)
        if eval_post_cp is None:
            return True

        actual_loss = eval_pre_cp - eval_post_cp
        # If user loses less than half the captured value, there's
        # tactical compensation. The "free" claim is misleading.
        if actual_loss < captured_value * _RECOVERY_THRESHOLD:
            logger.info(
                f"[threat_verifier] 'free capture' claim suppressed: "
                f"captured value {captured_value}cp, actual loss {actual_loss}cp "
                f"at depth {_VERIFY_DEPTH} (recovery threshold "
                f"{captured_value * _RECOVERY_THRESHOLD:.0f}cp)"
            )
            return False

    except Exception as exc:
        logger.warning(f"[threat_verifier] engine call failed: {exc}")
        return True

    return True
