import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Chessboard } from "react-chessboard";
import { ArrowRight, Check, ChevronDown, Code } from "lucide-react";
import { API } from "@/App";

const FEN=["6k1/6b1/8/8/8/2N5/8/R5K1 w - - 0 1","6k1/6b1/8/3N4/8/8/8/R5K1 b - - 1 1","6k1/8/8/3N4/8/8/8/b5K1 w - - 0 2"];
const FAQ=[["What rating range is ChessGuru for?","ChessGuru is built for players rated 600–1500 who feel stuck."],["How is this different from ordinary analysis?","Ordinary analysis names a bad move. ChessGuru finds the habit behind repeated mistakes and turns your positions into practice."],["Does it work with Chess.com and Lichess?","Yes. Connect the account where you already play so coaching can use positions you actually reached."],["Does AI decide whether a move is good?","No. Board and engine facts ground the explanation; AI does not invent what happened."],["Will one good game be called improvement?","No. One result is encouraging, not proof. Later games provide independent evidence."]];
const Board=({fen,mark,label})=><div role="img" aria-label={label} className="overflow-hidden shadow-2xl"><Chessboard position={fen} arePiecesDraggable={false} customLightSquareStyle={{backgroundColor:"#e7dcc5"}} customDarkSquareStyle={{backgroundColor:"#695d4b"}} customSquareStyles={mark}/></div>;
const CTA=({children,onClick,testid,quiet})=><button onClick={onClick} data-testid={testid} className={quiet?"min-h-12 rounded-full border border-black/20 px-7 text-sm font-semibold":"inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#b97917] px-7 text-sm font-bold text-white shadow-lg"}>{children}</button>;

export default function LandingEditorial(){
 const nav=useNavigate(),[dev,setDev]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>{fetch(`${API}/auth/status`).then(r=>r.json()).then(d=>setDev(d.dev_mode===true)).catch(()=>{});},[]);
 const login=async()=>{try{const d=await(await fetch(`${API}/auth/google/login`)).json();if(d.auth_url)window.location.href=d.auth_url;else alert("Login failed. Please try again.");}catch{alert("Login failed. Please try again.");}};
 const devLogin=async()=>{setLoading(true);try{const d=await(await fetch(`${API}/auth/dev-login`,{credentials:"include"})).json();if(d.status==="ok")window.location.href=sessionStorage.getItem("post_auth_redirect")||"/dashboard";}finally{setLoading(false);}};
 const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
 return <div className="min-h-screen overflow-hidden bg-[#f4efe5] text-[#181710]"><header className="fixed inset-x-0 top-0 z-50 border-b border-black/10 bg-[#f4efe5]/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><span className="flex items-center gap-2 font-bold"><img src="/chessguru-logo.svg" alt="" className="h-7 w-7"/>ChessGuru</span><nav className="hidden gap-7 text-sm md:flex"><button onClick={()=>scroll("how")}>How it works</button><button onClick={()=>scroll("faq")}>FAQ</button><button onClick={()=>nav("/pricing")}>Pricing</button></nav><div className="flex gap-3">{dev&&<button onClick={devLogin} data-testid="dev-login-button" className="hidden sm:flex"><Code className="h-4 w-4"/>{loading?"...":"Dev"}</button>}<button onClick={()=>nav("/login")} data-testid="signin-link" className="hidden sm:block">Sign in</button><button onClick={login} data-testid="login-button" className="rounded-full bg-[#181710] px-5 py-2.5 text-sm text-white">Start free</button></div></div></header>
 <main><section className="pt-32"><div className="mx-auto grid max-w-6xl gap-14 px-5 pb-24 lg:grid-cols-2 lg:items-center"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#986618]">Personal coaching from your own games</p><h1 className="font-heading text-5xl font-bold leading-[.95] tracking-[-.05em] sm:text-7xl">Your games already show what to work on next.</h1><p className="mt-7 text-lg leading-8 text-[#5b584e]">ChessGuru finds the mistake you repeat and turns positions from your games into a plan for breaking it.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><CTA onClick={login} testid="hero-cta-button">Connect my games <ArrowRight className="h-4 w-4"/></CTA><CTA onClick={()=>scroll("how")} testid="learn-more-button" quiet>Watch the loop</CTA></div><p className="mt-6 flex gap-2 text-xs text-[#716d62]"><Check className="h-4 w-4 text-teal-700"/>Free to start · Chess.com + Lichess</p></div><div className="relative pb-8"><Board fen={FEN[1]} mark={{d5:{background:"rgba(244,180,0,.58)"},a1:{background:"rgba(190,54,49,.62)"}}} label="Legal example where moving the knight opens the bishop diagonal to the rook"/><div className="relative -mt-8 mx-4 border-l-4 border-[#b97917] bg-[#fffaf0] p-5 shadow-xl sm:-mt-16 sm:max-w-sm"><b className="text-xs uppercase tracking-widest text-[#986618]">Example coaching moment · Nd5?</b><p className="mt-3 text-sm font-semibold">Your knight moved, but it was blocking the bishop's path to your rook on a1.</p><p className="mt-2 text-xs text-[#6c675c]">Before moving a piece, check what line it was closing.</p></div></div></div></section>
 <section className="bg-[#1d201b] py-24 text-[#f8f1e4]"><div className="mx-auto max-w-6xl px-5"><h2 className="font-heading text-4xl font-bold sm:text-6xl">A blunder is one move.<br/>A pattern is what keeps costing you games.</h2><div className="mt-14 grid gap-5 md:grid-cols-3">{[["Before",FEN[0],{c3:{background:"#c99228"}}, "The knight blocks the bishop's path."],["Blind spot",FEN[1],{d5:{background:"#c99228"},a1:{background:"#a6423c"}},"Nd5 looks active—but opens the diagonal."],["Reason",FEN[2],{a1:{background:"#a6423c"}},"...Bxa1 wins the rook."]].map(x=><article key={x[0]} className="border-t border-white/20 pt-4"><p className="mb-4 text-xs uppercase tracking-widest text-[#d7a24d]">{x[0]}</p><Board fen={x[1]} mark={x[2]} label={x[3]}/><p className="mt-4 text-sm text-[#d3ccbd]">{x[3]}</p></article>)}</div><p className="mt-5 text-xs text-[#8f8b80]">Demonstration position. The sequence is legal and board-verified.</p></div></section>
 <section id="how" className="py-24"><div className="mx-auto max-w-5xl px-5"><p className="text-xs font-bold uppercase tracking-widest text-[#986618]">One continuous coaching loop</p><h2 className="mt-4 font-heading text-5xl font-bold">Less dashboard. More direction.</h2><div className="mt-12 border-t border-black/15">{[["01","Notice","Find a mistake in a game you played."],["02","Explain","Name the reason in language you remember."],["03","Practise","Turn that position into a focused rep."],["04","Check again","Use later games as evidence—not one good result."]].map(x=><div key={x[0]} className="grid gap-3 border-b border-black/15 py-7 sm:grid-cols-[70px_1fr_2fr]"><span className="font-mono text-[#986618]">{x[0]}</span><b className="text-xl">{x[1]}</b><p className="text-[#676359]">{x[2]}</p></div>)}</div></div></section>
 <section id="faq" className="bg-[#ded4c2] py-24"><div className="mx-auto grid max-w-5xl gap-10 px-5 lg:grid-cols-[.7fr_1.3fr]"><h2 className="font-heading text-4xl font-bold">Questions, answered plainly.</h2><div className="border-t border-black/15">{FAQ.map(x=><details key={x[0]} className="group border-b border-black/15"><summary className="flex cursor-pointer list-none justify-between py-5 font-semibold">{x[0]}<ChevronDown className="h-4 w-4 group-open:rotate-180"/></summary><p className="pb-6 text-sm leading-7 text-[#625f55]">{x[1]}</p></details>)}</div></div></section>
 <section className="bg-[#1d201b] py-24 text-center text-white"><h2 className="mx-auto max-w-3xl px-5 font-heading text-5xl font-bold">Stop reviewing the same mistake. Start breaking it.</h2><div className="mt-9"><CTA onClick={login} testid="cta-button">Connect my games <ArrowRight className="h-4 w-4"/></CTA></div></section></main>
 <footer className="border-t border-white/10 bg-[#1d201b] py-10 text-[#8f897d]"><div className="mx-auto flex max-w-5xl flex-wrap justify-center gap-5 px-5 text-xs"><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund">Refunds</a><a href="/contact">Contact</a><a href="/pricing">Pricing</a></div></footer></div>;
}
